"""empty message

Revision ID: 13aaf77d2fdd
Revises: 38f80f63cdf1
Create Date: 2018-12-15 20:51:11.491936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13aaf77d2fdd'
down_revision = '38f80f63cdf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer', sa.String(length=100), nullable=False),
    sa.Column('project', sa.String(length=100), nullable=False),
    sa.Column('task', sa.String(length=100), nullable=True),
    sa.Column('datetime_start', sa.DateTime(), nullable=False),
    sa.Column('datetime_end', sa.DateTime(), nullable=True),
    sa.Column('time_correction', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('billable', sa.Boolean(), nullable=True),
    sa.Column('comment', sa.String(length=100), nullable=True),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timelog')
    # ### end Alembic commands ###
