"""empty message

Revision ID: 38f80f63cdf1
Revises: 
Create Date: 2018-12-14 21:30:14.015331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38f80f63cdf1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_bak')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bak',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.TEXT(), nullable=True),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('image_file', sa.TEXT(), nullable=True),
    sa.Column('password', sa.TEXT(), nullable=True)
    )
    # ### end Alembic commands ###
